import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import toast from "react-hot-toast";
import axios from "axios";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import { loginSchema } from "../utils/schemas";
import Button from "../components/Button/Button";
import Container from "../components/Container/Container";
import { FormGroup, FormInput, FormLabel } from "../components/Form";
import Title from "../components/Title/Title";
import ErrorText from "../components/ErrorText/ErrorText";
import Loading from "../components/Loading/Loading";

interface ILoginForm {
  email: string;
  pword: string;
}

const Login: NextPage = () => {
  const FormFields = [
    {
      label: "Email address",
      id: "email",
      type: "email",
      name: "email",
      placeholder: "Enter your email address",
    },
    {
      label: "Password",
      id: "pword",
      type: "password",
      name: "pword",
      placeholder: "Enter your password",
    },
  ];

  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<ILoginForm>({
    resolver: yupResolver(loginSchema),
  });

  const onSubmit = handleSubmit(async (data) => {
    try {
      setIsSubmitting(true);
      const res = await axios.post("/user/login", {
        email: data.email,
        password: data.pword,
      });

      document.cookie = `userId=${res.data._id}`;
      toast.success("Login successful");
    } catch (err: any) {
      toast.error(err.response?.data?.message || "An error occured");
    } finally {
      setIsSubmitting(false);
    }
  });

  return (
    <>
      <Head>
        <title>Techinnover Frontend Task | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Title>Login</Title>
        <form onSubmit={onSubmit} autoComplete="off">
          {FormFields.map((field) => (
            <FormGroup key={field.id}>
              <FormLabel htmlFor={field.id}>{field.label}</FormLabel>
              <FormInput
                dark
                {...register(field.name as any)}
                // @ts-ignore
                error={errors[field.name]?.message}
                type={field.type}
                id={field.id}
                name={field.name}
                placeholder={field.placeholder}
              />
              {/* @ts-ignore */}
              <ErrorText>{errors[field.name]?.message}</ErrorText>
            </FormGroup>
          ))}
          <Button type="submit">{isSubmitting ? <Loading /> : "Log in"}</Button>
        </form>
      </Container>
    </>
  );
};

export default Login;
